export const GET_BREEDS = {
    "REQUEST": "GET_BREEDS_REQUEST",
    "SUCCESS": "GET_BREEDS_SUCCESS",
    "FAILURE": "GET_BREEDS_FAILURE",
}

export const GET_CATS_BY_BREED = {
    "REQUEST": "GET_CATS_BY_BREED_REQUEST",
    "SUCCESS": "GET_CATS_BY_BREED_SUCCESS",
    "FAILURE": "GET_CATS_BY_BREED_FAILURE",
}

export const GET_CAT_DETAILS= {
    "REQUEST": "GET_CAT_DETAILS_REQUEST",
    "SUCCESS": "GET_CAT_DETAILS_SUCCESS",
    "FAILURE": "GET_CAT_DETAILS_FAILURE",
}

export const HAS_MORE = "HAS_MORE"


